variables:
    PLUGIN_NAME: 'OASwitchboard'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: main
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ojs/unit_tests.yml'
      - 'templates/groups/ojs/cypress_tests.yml'

.unit_test_template:
  before_script:
    - sed -i 's/api_key_secret = ""/api_key_secret = "$API_KEY_SECRET"/' /var/www/ojs/config.inc.php

.integration_tests_template:
  before_script:
    - export CYPRESS_OASPassword="$(echo $CYPRESS_OASPassword | base64 -d)"
    - sed -i 's/api_key_secret = ""/api_key_secret = "$API_KEY_SECRET"/' /var/www/ojs/config.inc.php

# Skip running Cypress tests on OJS (workaround)
ojs_integration_tests:
  rules:
    - when: never
